openapi: 3.0.3
info:
  title: DeviceAPI - AgroMate
  description: |-
   API di AgroMate per gestire gli ESP8266 associati all'utente
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0"
externalDocs:
  description: Github
  url: https://github.com/agromate-devs
servers:
  - url: https://b8kc0x92yj.execute-api.eu-central-1.amazonaws.com/
tags:
  - name: plant
    description: Gestisci piante assegnate al sensore
paths:
  /:
    get:
      tags:
        - plant
      summary: Lista dei sensori collegati ad un utente
      description: Lista dei sensori collegati ad un utente(sensor_uuid e user_uid)
      operationId: getSensorsByUserUid
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
            description: Firebase JWT Token
            format: JWT
            example: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJteS1wcm9qZWN0IiwiZXhwIjoxNTA5NjUwODAxLCJpYXQiOjE1MDk2NTQ0MDF9.F4iKO0R0wvHkpCcQoyrYttdGxE5FLAgDhbTJQLEHIBPsbL2WkLxXB9IGbDESn9rE7oxn89PJFRtcLn7kJwvdQkQcsPxn2RQorvDAnvAi1w3k8gpxYWo2DYJlnsi7mxXDqSUCNm1UCLRCW68ssYJxYLSg7B1xGMgDADGyYPaIx1EdN4dDbh-WeDyLLa7a8iWVBXdbmy1H3fEuiAyxiZpk2ll7DcQ6ryyMrU2XadwEr9PDqbLe5SrlaJsQbFi8RIdlQJSo_DZGOoAlA5bYTDYXb-skm7qvoaH5uMtOUb0rjijYuuxhNZvZDaBerEaxgmmlO0nQgtn12KVKjmKlisG79Q"
          required: true
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidResponse'
        '500':
          description: Body o richiesta invalida
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/InvalidRequest'
    post:
      tags:
        - plant
      summary: Aggiungi un sensore all'account
      description: Aggiungi un nuovo sensore all'account
      operationId: addPlant
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
            description: Firebase JWT Token
            format: JWT
            example: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJteS1wcm9qZWN0IiwiZXhwIjoxNTA5NjUwODAxLCJpYXQiOjE1MDk2NTQ0MDF9.F4iKO0R0wvHkpCcQoyrYttdGxE5FLAgDhbTJQLEHIBPsbL2WkLxXB9IGbDESn9rE7oxn89PJFRtcLn7kJwvdQkQcsPxn2RQorvDAnvAi1w3k8gpxYWo2DYJlnsi7mxXDqSUCNm1UCLRCW68ssYJxYLSg7B1xGMgDADGyYPaIx1EdN4dDbh-WeDyLLa7a8iWVBXdbmy1H3fEuiAyxiZpk2ll7DcQ6ryyMrU2XadwEr9PDqbLe5SrlaJsQbFi8RIdlQJSo_DZGOoAlA5bYTDYXb-skm7qvoaH5uMtOUb0rjijYuuxhNZvZDaBerEaxgmmlO0nQgtn12KVKjmKlisG79Q"
          required: true
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidPostResponse'
        '500':
          description: Body o richiesta invalida
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/InvalidRequest'
    delete:
      tags:
        - plant
      summary: Rimuovi un sensore all'account
      description: Rimuovi un nuovo sensore all'account
      operationId: removeSensor
      parameters:
        - name: device_id
          in: path
          description: Sensor UUID
          required: true
          schema:
            type: string
        - in: header
          name: Authorization
          schema:
            type: string
            description: Firebase JWT Token
            format: JWT
            example: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJteS1wcm9qZWN0IiwiZXhwIjoxNTA5NjUwODAxLCJpYXQiOjE1MDk2NTQ0MDF9.F4iKO0R0wvHkpCcQoyrYttdGxE5FLAgDhbTJQLEHIBPsbL2WkLxXB9IGbDESn9rE7oxn89PJFRtcLn7kJwvdQkQcsPxn2RQorvDAnvAi1w3k8gpxYWo2DYJlnsi7mxXDqSUCNm1UCLRCW68ssYJxYLSg7B1xGMgDADGyYPaIx1EdN4dDbh-WeDyLLa7a8iWVBXdbmy1H3fEuiAyxiZpk2ll7DcQ6ryyMrU2XadwEr9PDqbLe5SrlaJsQbFi8RIdlQJSo_DZGOoAlA5bYTDYXb-skm7qvoaH5uMtOUb0rjijYuuxhNZvZDaBerEaxgmmlO0nQgtn12KVKjmKlisG79Q"
          required: true
      responses:
        '200':
          description: Operazione eseguita con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidDeleteResponse'
        '500':
          description: Body o richiesta invalida
          content:
            text/html:
              schema:
                $ref: '#/components/schemas/InvalidRequest'
components:
  schemas:
    ValidResponse:
      properties:
        error:
          type: boolean
          format: boolean
          example: false
        message:
          type: object
          items: 
            $ref: '#/components/schemas/Sensor'
          properties:
            device_id:
              type: string
              format: string
              example: Ciao
    ValidPostResponse:
      properties:
        error:
          type: boolean
          format: boolean
          example: false
        message:
          type: string
          example: Device added successfully
    ValidDeleteResponse:
      properties:
        error:
          type: boolean
          format: boolean
          example: false
        message:
          type: string
          example: Device deleted successfully
    Sensors:
      required:
        - device_id
      type: array
      items: 
        $ref: '#/components/schemas/Sensor'
    Sensor:
      properties:
        device_id:
          type: string
          format: string
          example: Ciao
    ValidRequest:
      type: string
      example: OK
    InvalidRequest:
      type: string
      example: Internal Server Error in endpoint_name
  requestBodies:
    WishList:
      description: WishList object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Sensors'