on:
    push:
      branches:
        - main
name: 🚀 Build and Deploy Docs
jobs:
    web-deploy:
      name: 🎉 Deploy
      runs-on: ubuntu-latest
      steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
  
      - name: Set up Node.JS
        uses: actions/setup-node@v2
        with:
          node-version: '16'
        
      - name: 🔨 Install Redocly
        run: |
            sudo npm i -g @redocly/cli

      - name: 🔨 Build docs
        run: |
            mkdir dist
            cd dist
            redocly build-docs ../docs/wishlist.yaml -o wishlist.html
            redocly build-docs ../docs/plant_info.yaml -o plant_info.html
            
      - name: 📂 Deploy docs
        uses: crazy-max/ghaction-github-pages@v2
        with:
            build_dir: dist
        env:
            GITHUB_TOKEN: ${{ secrets.TOKEN }}
  
          
          